services:
  zipkin:
    # Image basierend auf nginx als Webserver
    #image: openzipkin/zipkin:3.3.0
    #image: openzipkin/zipkin:3.2.1
    #image: openzipkin/zipkin:3.1.1
    image: openzipkin/zipkin:3.1.0
    ports:
      - published: 9411
        target: 9411
    restart: always
    container_name: zipkin
    #extra_hosts: ['host.docker.internal']
